# Generated by Django 5.2.3 on 2025-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='numero_edificios_residenciales',
            field=models.IntegerField(default=0),
        ),
    ]
